login:
  weibo_client_id:
    default: ''
  weibo_client_secret:
    default: ''
  renren_client_id:
    default: ''
  renren_client_secret:
    default: ''
  qq_connect_client_id:
    default: ''
  qq_connect_client_secret:
    default: ''
  douban_client_id:
    default: ''
  douban_client_secret:
    default: ''
plugins:
  zh_l10n_enabled:
    default: true
  zh_l10n_weibo_client_id:
    default: ''
  zh_l10n_weibo_client_secret:
    default: ''
  zh_l10n_renren_client_id:
    default: ''
  zh_l10n_renren_client_secret:
    default: ''
  zh_l10n_qq_connect_client_id:
    default: ''
  zh_l10n_qq_connect_client_secret:
    default: ''
  zh_l10n_douban_client_id:
    default: ''
  zh_l10n_douban_client_secret:
    default: ''
